config/routes.rb
Rails.application.routes.draw do
resources :orders
root to: 'orders#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	 def new
    @client_token = Braintree::ClientToken.generate
  end

  def create
    nonce = params[:payment_method_nonce]
    puts nonce
   # render action: :new and return unless nonce
    result = Braintree::Transaction.sale(
      amount: "50.00",
      payment_method_nonce: nonce
    )
    @result = result
	@success = result.success?
	@transaction_id = result.transaction.id
    flash[:notice] = "Success! Time, like Nonces, is precious. Use it well." if result.success?
    flash[:alert] = "The nonces have eaten your sale. #{result.transaction.processor_response_text}" unless result.success?
    #redirect_to action: :new
    render 'result'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BTPayment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/new.html.erb
<h2>Buy Apple Keyboard $50</h2>

<%= render 'payments/form' %>

app/views/orders/result.html.erb
<h2>Result</h2>
<%= @success %>
<br/>
<%= @transaction_id %>
<br/>
<%= @result.inspect %>


<div class="container">
         
  <table class="table table-condensed" >
   
    <tbody>
      <tr class="success">
        <td>Success</td>
        <td><%= @success %></td>
        
      </tr>
      <tr class="danger">
        <td>Transaction ID</td>
        <td><%= @transaction_id %></td>
        
      </tr>
      <tr class="info">
        <td>Type</td>
        <td><%= @result.transaction.type%></td>
        
      </tr>
        <tr class="success">
        <td>Amount</td>
        <td><%= @result.transaction.amount %></td>
        
      </tr>
      <tr class="danger">
        <td>Status</td>
        <td><%= @result.transaction.status%></td>
        
      </tr>
      <tr class="info">
        <td>Created at</td>
        <td><%= @result.transaction.created_at%></td>
        
      </tr>
    </tbody>
  </table>
  <a href="/" type="button" class="btn btn-primary active" role="button">Home</a>
</div>

app/views/payments/_form.html.erb
<%= form_tag orders_path, method: 'post' do %>
  <div id="dropin"></div>
  <input type="submit" class="btn btn-primary active" role="button" value="Pay $50">
<% end %>
<%= @params %>
<%=@client_token%>

<script type="text/javascript">
  function setupBT() {
    braintree.setup("<%=@client_token%>", 'dropin', {
      container: 'dropin'
    });
  }
  if (window.addEventListener)
    window.addEventListener("load", setupBT, false);
  else if (window.attachEvent)
    window.attachEvent("onload", setupBT);
  else window.onload = setupBT;
  </script>
</script>